version: '3'

services:
  rabbitmq:
    image: andrewkeig/rabbitmq-mqtt-enabled
    volumes:
      - .:/rb
    ports:
      - "15672:15672"
      - "5672:5672"
      - "1883:1883"
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - rabbitmq
