# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-11-28 15:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_id', models.CharField(max_length=20)),
                ('lat', models.FloatField(help_text='Latitude')),
                ('lng', models.FloatField(help_text='Longitude')),
            ],
        ),
    ]
